### ISSUE TITLE
How to use the addon

### ISSUE THREAD

**Issue by NernBrot** [MBedwars/LevelShop-Addon#2]
Very sorry, respected code creator
I'm bothering you again
I used your extension with the latest API
But I still don't know how to fill it out in spawners.yml to link it with your extension
I hope you can reply to my question amidst your busy schedule
Wishing you a happy life and all the best

**Comment by MrEAlderson** [comment]
Hi,
https://wiki.mbedwars.com/en/Configuration/Spawners

add a new spawner to spawners.yml and include these configs:
```yaml
custom-handler: "lvl-shop"
custom-handler-config:
  level-amount: 1
```
